<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timeTable [
<!ELEMENT timeTable (complexes, lessons)>
<!ELEMENT complexes (complex+)>
<!ELEMENT lessons (lesson+)>
<!ELEMENT complex (name, address)>
<!ELEMENT lesson (date, time)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ATTLIST complex code ID #REQUIRED>
<!ATTLIST lesson no CDATA #REQUIRED>
<!ATTLIST lesson complex IDREF #REQUIRED>
]>
<timeTable>
  <complexes>
    <complex code="c1">
      <name>Учебный корпус A</name>
      <address>Москва, ул. Ленина, 10</address>
    </complex>
    <complex code="c2">
      <name>Учебный корпус B</name>
      <address>Москва, ул. Пушкина, 25</address>
    </complex>
  </complexes>
  <lessons>
    <lesson no="1" complex="c1">
      <date>2026-02-09</date>
      <time>14:00</time>
    </lesson>
    <lesson no="2" complex="c2">
      <date>2026-02-10</date>
      <time>16:00</time>
    </lesson>
    <lesson no="3" complex="c1">
      <date>2026-02-11</date>
      <time>10:00</time>
    </lesson>
  </lessons>
</timeTable>
